version: "2"
run:
  timeout: 5m
  tests: false
linters:
  settings:
    staticcheck:
      checks:
        - all
        # Incorrect or missing package comment.
        # https://staticcheck.dev/docs/checks/#ST1000
        - -ST1000
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tests$
formatters:
  exclusions:
    generated: lax
