name: test

on: [workflow_call] # allow this workflow to be called from other workflows

jobs:
  helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.4.1
        with:
          compose-file: ./docker-compose.yml
          compose-flags: '--env-file ./tests/.env.dev'
          up-flags: '--exit-code-from tester-helper'
          services: 'tester-helper'

  states:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.4.1
        with:
          compose-file: ./docker-compose.yml
          compose-flags: '--env-file ./tests/.env.dev'
          up-flags: '--exit-code-from tester-state'
          services: 'tester-state'

  datasources:
    runs-on: ubuntu-latest
    needs: [states]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.4.1
        with:
          compose-file: ./docker-compose.yml
          compose-flags: '--env-file ./tests/.env.dev'
          up-flags: '--exit-code-from tester-ds'
          services: 'tester-ds'

  pipelines:
    runs-on: ubuntu-latest
    needs: [states, datasources]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.4.1
        with:
          compose-file: ./docker-compose.yml
          compose-flags: '--env-file ./tests/.env.dev'
          up-flags: '--exit-code-from tester-pipe'
          services: 'tester-pipe'
