# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker images
        run: docker build -f ./Dockerfile -t local .

      - name: Run tests
        run: docker run -it -w/usr/src/app -v $PWD:/usr/src/app local go test -v -o /usr/src/app/app.test