name: release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/_test.yml # use the callable tests job to run tests

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate Release Notes and Publish
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter.yml'
          name: 'Release ${{ github.ref_name }}'
          tag: ${{ github.ref_name }}
          publish: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
