name: test

on: [workflow_call] # allow this workflow to be called from other workflows

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yml
          compose-flags: "--env-file ./tests/.env.dev"
          up-flags: "--abort-on-container-exit"
